---
# Second project for Team Alpha - API service
# Branch: team-alpha-project-api in testing-grounds repo
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: api
  namespace: kargo-team-alpha-team-alpha-project-api
spec:
  promotionPolicies:
    - stage: dev
      autoPromotionEnabled: true
    - stage: prod
      autoPromotionEnabled: false

