# VirtualMachine with status Healthy (Running) - from resource_customizations/kubevirt.io/VirtualMachine/testdata/healthy_ready.yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-healthy
  namespace: kubevirt-health-test
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1alpha3
spec:
  running: false  # set false to avoid virt-launcher starting QEMU (no PID logs)
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: vm-healthy
        kubevirt.io/size: small
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            name: default
        machine:
          type: virt
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      volumes:
      - containerDisk:
          image: quay.io/kubevirt/cirros-container-disk-demo
        name: containerdisk
      - cloudInitNoCloud:
          userDataBase64: SGkuXG4=
        name: cloudinitdisk
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-09-10T16:17:44Z"
    status: "True"
    type: Ready
  created: true
  printableStatus: Running
  ready: true
  volumeSnapshotStatuses:
  - enabled: false
    name: containerdisk
    reason: Snapshot is not supported for this volumeSource type [containerdisk]
  - enabled: false
    name: cloudinitdisk
    reason: Snapshot is not supported for this volumeSource type [cloudinitdisk]
