# VirtualMachine with status Progressing (No status available) - from testdata/progressing_nostatus.yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-progressing-nostatus
  namespace: kubevirt-health-test
  annotations: {}
  creationTimestamp: "2021-07-16T00:41:10Z"
  labels:
    app.kubernetes.io/instance: testv
spec:
  running: false  # set false to avoid virt-launcher starting QEMU (no PID logs)
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: vm-progressing-nostatus
        kubevirt.io/size: small
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            name: default
        machine:
          type: virt
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      volumes:
      - containerDisk:
          image: quay.io/kubevirt/cirros-container-disk-demo
        name: containerdisk
      - cloudInitNoCloud:
          userDataBase64: SGkuXG4=
        name: cloudinitdisk
status:
  volumeSnapshotStatuses:
  - enabled: false
    name: containerdisk
    reason: Volume type has no StorageClass defined
  - enabled: false
    name: cloudinitdisk
    reason: Volume type has no StorageClass defined
