---
# ApplicationSet using SCM Provider Generator to auto-discover team repositories
# Based on Argo CD SCM Provider Generator documentation
# https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-SCM-Provider/#github
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-team-projects-scm
  namespace: argocd
spec:
  generators:
    - scmProvider:
        cloneProtocol: https
        
        github:
          organization: csz-ghorg
          tokenRef:
            secretName: application-set-secret
            key: git-token
          
          allBranches: true
        
        filters:
          - pathsExist: 
              - kargo-manifests
            # repositoryMatch: ^team-.*
            # labelMatch: kargo-enabled
  
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  
  template:
    metadata:
      # Use repository name and branch for unique app names
      name: '{{ .repository }}-{{ .branch }}'
      annotations:
        kargo.akuity.io/authorized-project: '{{ .repository }}-{{ .branch }}'
        team: '{{ .repository }}'
      labels:
        repository: '{{ .repository }}'
        branch: '{{ .branch }}'
    
    spec:
      # Project name - you'll need to create AppProjects for each repository/team
      # For now, using a default project, but you can template this based on repository name
      project: default
      
      source:
        # The SCM generator provides the clone URL
        repoURL: '{{ .url }}'
        targetRevision: '{{ .branch }}'
        path: kargo-manifests
      
      destination:
        server: https://cluster-kargo:6445
        namespace: '{{ .repository }}-{{ .branch }}'
      
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

