---
# ApplicationSet for Kargo Multi-Tenancy
# Uses List Generator - manually add each team/branch
# Projects are HARDCODED for security
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-multi-tenant
  namespace: akuity
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  
  generators:
    # List generator - add team branches here
    - list:
        elements:
          # Team Alpha - Webapp Project
          - team: team-alpha
            branch: team-alpha-webapp
            project: team-alpha  # HARDCODED
          
          # Team Alpha - API Project  
          - team: team-alpha
            branch: team-alpha-api
            project: team-alpha  # HARDCODED
          
          # Team Beta - Mobile Project
          - team: team-beta
            branch: team-beta-mobile
            project: team-beta  # HARDCODED
          
          # To add new team/project, just add entry here:
          # - team: team-gamma
          #   branch: team-gamma-dashboard
          #   project: team-gamma
  
  template:
    metadata:
      name: '{{.branch}}'
      annotations:
        # Kargo authorization - links Application to Kargo Stage
        kargo.akuity.io/authorized-stage: '{{.team}}:{{.branch}}'
        team: '{{.team}}'
      labels:
        team: '{{.team}}'
    
    spec:
      project: '{{.project}}'  # From list element (hardcoded per team)
      
      source:
        repoURL: https://github.com/csz-akuity/testing-grounds.git
        targetRevision: '{{.branch}}'
        path: kargo-manifests  # Each branch has kargo-manifests/
      
      destination:
        server: https://cluster-kargo:6445  # Self-hosted Kargo cluster
        namespace: '{{.branch}}'  # One namespace per project
      
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
