---
# Minimal AppProject for Team Alpha - Testing
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-alpha-minimal
  namespace: akuity
spec:
  description: Minimal Team Alpha project for testing
  
  sourceRepos:
    - '*'
  
  destinations:
    - namespace: '*'
      server: '*'
  
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
