---
# AppProject for Team Beta
# Maps to Argo CD SSO groups for RBAC isolation
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-beta
  namespace: argocd
spec:
  description: Team Beta Kargo projects
  sourceRepos:
    - 'https://github.com/csz-akuity/testing-grounds.git'
    - '*'  # Required for Kargo git promotions
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
    - namespace: '*'
      server: https://cluster-kargo:6445
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'