apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: agent-images
  namespace: agent-images
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: argo-cd-test
  namespace: agent-images
spec:
  freightCreationPolicy: Automatic
  interval: 5m0s
  subscriptions:
    - image:
        discoveryLimit: 20
        imageSelectionStrategy: SemVer
        repoURL: quay.io/akuity/agent
        strictSemvers: true
    - image:
        discoveryLimit: 20
        imageSelectionStrategy: SemVer
        repoURL: quay.io/akuity/argocd
        strictSemvers: true
    - image:
        discoveryLimit: 20
        imageSelectionStrategy: SemVer
        repoURL: quay.io/argoprojlabs/argocd-image-updater
        strictSemvers: true
    - image:
        discoveryLimit: 20
        imageSelectionStrategy: SemVer
        repoURL: quay.io/akuity/redis
        strictSemvers: true
    - image:
        discoveryLimit: 20
        imageSelectionStrategy: SemVer
        repoURL: quay.io/akuity/haproxy
        strictSemvers: true