---
# ApplicationSet using Matrix Generator - simpler approach like the tutorial
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: team-applications-scm
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchExpressions:
                - {key: kubernetes.io/hostname, operator: In, values: [cluster-local-k3d]}
          - list:
              elements:
              - env: dev
              - env: staging
              - env: prod
  template:
    metadata:
      name: 'kargo-quickstart-template-{{env}}'
      annotations:
        kargo.akuity.io/authorized-stage: 'kargo-quickstart-template:{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/csz-ghorg/kargo-quickstart-template.git
        targetRevision: env/{{env}}
        path: app/env/{{env}}
      destination:
        name: '{{name}}'
        namespace: 'kargo-quickstart-template-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
