apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slow-plugin-app
spec:
  destination:
    name: local-k3d
    namespace: slow-plugin-test
  source:
    repoURL: https://github.com/csz-ghorg/testing-grounds.git
    targetRevision: context-deadline
    path: context-deadline/manifests
    plugin:
      name: slow-manifests
  project: default
  syncPolicy:
    automated: {}