apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slow-plugin-app
spec:
  destination:
    name: local-k3d
    namespace: slow-plugin-test
  source:
    path: context-deadline/manifests/
    repoURL: https://github.com/csz-ghorg/testing-grounds.git
    targetRevision: context-deadline
    plugin:
      name: slow-manifests-v1.0
  sources: []
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
