apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kedacore.github.io/charts
    chart: keda
    targetRevision: 2.13.1
  destination:
    server: http://cluster-temp-cluster:8001
    namespace: operations
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
