---
# Dev stage - auto-promotes from warehouse
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: default
spec:
  subscriptions:
    warehouses:
      - name: team-alpha-webapp
  promotionMechanisms:
    - gitUpdates:
        - repoURL: https://github.com/csz-akuity/testing-grounds.git
          branch: team-alpha-project-webapp
          kustomize:
            images:
              - image: nginx
              - image: postgres

---
# Staging stage - requires manual promotion
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: default
spec:
  subscriptions:
    upstreamStages:
      - name: dev
  promotionMechanisms:
    - gitUpdates:
        - repoURL: https://github.com/csz-akuity/testing-grounds.git
          branch: team-alpha-project-webapp
          kustomize:
            images:
              - image: nginx
              - image: postgres
  verification:
    analysisTemplates:
      - name: verify-deployment-health

---
# Production stage - requires manual promotion with verification
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: default
spec:
  subscriptions:
    upstreamStages:
      - name: staging
  promotionMechanisms:
    - gitUpdates:
        - repoURL: https://github.com/csz-akuity/testing-grounds.git
          branch: team-alpha-project-webapp
          kustomize:
            images:
              - image: nginx
              - image: postgres
  verification:
    analysisTemplates:
      - name: verify-deployment-health
