---
# Stages for team-alpha-project-webapp
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: default
spec:
  # This stage auto-promotes when new Freight arrives
  promotionPolicies:
    - stage: dev
      autoPromotionEnabled: true
  # Subscribe to the warehouse for new Freight
  subscriptions:
    warehouses:
      - name: webapp
  # Promote to staging stage
  promotionMechanisms:
    argoCDAppUpdates:
      - appName: webapp-dev
        sourceUpdates:
          - repoURL: https://github.com/csz-akuity/testing-grounds.git
            branch: team-alpha-project-webapp
            kustomize:
              images:
                - image: nginx
                  key: image
                - image: postgres
                  key: image

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: default
spec:
  # This stage requires manual promotion
  promotionPolicies:
    - stage: staging
      autoPromotionEnabled: false
  # Subscribe to dev stage for promotions
  subscriptions:
    upstreamStages:
      - name: dev
  # Promote to prod stage
  promotionMechanisms:
    argoCDAppUpdates:
      - appName: webapp-staging
        sourceUpdates:
          - repoURL: https://github.com/csz-akuity/testing-grounds.git
            branch: team-alpha-project-webapp
            kustomize:
              images:
                - image: nginx
                  key: image
                - image: postgres
                  key: image

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: default
spec:
  # This stage requires manual promotion
  promotionPolicies:
    - stage: prod
      autoPromotionEnabled: false
  # Subscribe to staging stage for promotions
  subscriptions:
    upstreamStages:
      - name: staging
  # Deploy to production
  promotionMechanisms:
    argoCDAppUpdates:
      - appName: webapp-prod
        sourceUpdates:
          - repoURL: https://github.com/csz-akuity/testing-grounds.git
            branch: team-alpha-project-webapp
            kustomize:
              images:
                - image: nginx
                  key: image
                - image: postgres
                  key: image