---
# Stage: Dev
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-team-alpha-team-alpha-project-webapp
spec:
  subscriptions:
    warehouse: webapp
  
  promotionTemplate:
    spec:
      steps:
        # Clone the config repo
        - uses: git-clone
          config:
            repoURL: https://github.com/csz-akuity/argocd-example-apps.git
            branch: main
            checkout:
              - branch: main
                create: true
                path: ./config
        
        # Update image with new version
        - uses: kustomize-set-image
          config:
            path: ./config/guestbook
            images:
              - image: public.ecr.aws/nginx/nginx
        
        # Commit changes
        - uses: git-commit
          config:
            path: ./config
            messageFromSteps:
              - kustomize-set-image
        
        # Push to trigger Jenkins pipeline
        - uses: git-push
          config:
            path: ./config
            targetBranch: team-alpha-webapp-dev
  
  # Verification - Wait for deployment to be healthy
  # This runs in the platform cluster but checks app cluster via kubeconfig
  verification:
    analysisTemplates:
      - name: verify-deployment-health
    
    # Runs with workload identity
    analysisRunMetadata:
      annotations:
        iam.gke.io/gcp-service-account: kargo-team-alpha@project-id.iam.gserviceaccount.com

---
# Stage: Prod
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-team-alpha-team-alpha-project-webapp
spec:
  subscriptions:
    upstreamStages:
      - name: dev
  
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/csz-akuity/argocd-example-apps.git
            branch: main
            checkout:
              - branch: main
                create: true
                path: ./config
        
        - uses: kustomize-set-image
          config:
            path: ./config/guestbook
            images:
              - image: public.ecr.aws/nginx/nginx
        
        - uses: git-commit
          config:
            path: ./config
            messageFromSteps:
              - kustomize-set-image
        
        - uses: git-push
          config:
            path: ./config
            targetBranch: team-alpha-webapp-prod
  
  verification:
    analysisTemplates:
      - name: verify-deployment-health
      - name: verify-rollout-complete
    
    analysisRunMetadata:
      annotations:
        iam.gke.io/gcp-service-account: kargo-team-alpha@project-id.iam.gserviceaccount.com
