---
# Dev stage - auto-promotes from warehouse
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: team-alpha-webapp
spec:
  # Request Freight directly from the warehouse
  requestedFreight:
    - origin:
        kind: Warehouse
        name: team-alpha-webapp
      sources:
        direct: true

---
# Staging stage - requires manual promotion from dev
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: team-alpha-webapp
spec:
  # Request Freight from dev stage
  requestedFreight:
    - origin:
        kind: Warehouse
        name: team-alpha-webapp
      sources:
        stages:
          - dev
  
  # Simple verification
  verification:
    analysisTemplates:
      - name: verify-deployment-health

---
# Production stage - requires manual promotion from staging
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: team-alpha-webapp
spec:
  # Request Freight from staging stage
  requestedFreight:
    - origin:
        kind: Warehouse
        name: team-alpha-webapp
      sources:
        stages:
          - staging
  
  # Verification before considering promotion successful
  verification:
    analysisTemplates:
      - name: verify-deployment-health