---
# Warehouse for team-alpha-project-webapp
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: team-alpha-webapp
  namespace: team-alpha-webapp
spec:
  interval: 5m0s
  
  subscriptions:
    # Watch container images - using public nginx for testing
    - image:
        repoURL: nginx
        semverConstraint: ^1.26
        discoveryLimit: 5
        
    # Watch Git repo for config changes
    - git:
        repoURL: https://github.com/csz-akuity/testing-grounds.git
        branch: team-alpha-project-webapp
