---
# Dedicated namespace for Team Alpha's Kargo resources
# Kargo controller will create service accounts automatically
apiVersion: v1
kind: Namespace
metadata:
  name: kargo-team-alpha
  annotations:
    # For GCP Workload Identity (if using)
    iam.gke.io/gcp-service-account: kargo-team-alpha@project-id.iam.gserviceaccount.com

