---
apiVersion: v1
kind: Namespace
metadata:
  name: kargo-team-beta
  annotations:
    iam.gke.io/gcp-service-account: kargo-team-beta@project-id.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kargo-agent
  namespace: kargo-team-beta
  annotations:
    iam.gke.io/gcp-service-account: kargo-team-beta@project-id.iam.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kargo-agent
  namespace: kargo-team-beta
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-agent
subjects:
  - kind: ServiceAccount
    name: kargo-agent
    namespace: kargo-team-beta

