apiVersion: v1
kind: ConfigMap
metadata:
  name: team-alpha-webapp-content
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
    <title>Team Alpha WebApp - Staging</title>
    <style>
      body { font-family: Arial, sans-serif; margin: 40px; background-color: #fff3e0; }
      h1 { color: #ef6c00; }
      .stage { background-color: #ff9800; color: white; padding: 10px; border-radius: 5px; }
    </style>
    </head>
    <body>

    <h1>Team Alpha WebApp</h1>
    <div class="stage">Environment: Staging</div>
    <p>This is the staging environment for Team Alpha's web application.</p>
    <p>Ready for testing and validation before production deployment.</p>
    <p>Latest deployment: <span id="timestamp"></span></p>
    
    <script>
      document.getElementById('timestamp').textContent = new Date().toISOString();
    </script>

    </body>
    </html>
