apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- configmap.yaml

patches:
- target:
    kind: Service
    name: team-alpha-webapp
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30092
