---
# Team Beta - Mobile project
# Branch: team-beta-project-mobile in testing-grounds repo
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: mobile
  namespace: kargo-team-beta-team-beta-project-mobile
spec:
  promotionPolicies:
    - stage: dev
      autoPromotionEnabled: true
    - stage: prod
      autoPromotionEnabled: false

