apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gate-service
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    target-revision: HEAD
spec:
  project: default
  source:
    repoURL: https://github.com/csz-ghorg/testing-grounds.git
    targetRevision: HEAD
    path: http-gate-testing/manifests
  destination:
    server: http://cluster-local-k3d:8001
    namespace: gate-service
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
