apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-alpha-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: team-alpha-webapp
  template:
    metadata:
      labels:
        app: team-alpha-webapp
    spec:
      containers:
      - name: nginx 
        image: nginx:placeholder
        ports:
        - containerPort: 80
        volumeMounts:
        - name: content
          mountPath: /usr/share/nginx/html
          readOnly: true
      volumes:
      - name: content
        configMap:
          name: team-alpha-webapp-content
