apiVersion: v1
kind: Service
metadata:
  name: team-alpha-webapp
spec:
  type: NodePort
  selector:
    app: team-alpha-webapp
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 80
    nodePort: placeholder
